server:
  port: 8080

spring:
  datasource:
    url: ${DB_URL}
    username: ${DB_USER}
    password: ${DB_PASS}
    driver-class-name: com.mysql.cj.jdbc.Driver

  jpa:
    # update ?????????????????? (??????????????)
    hibernate:
      ddl-auto: update
    show-sql: true # ????? SQL ???????
    database-platform: org.hibernate.dialect.MySQL8Dialect

# 🚀 新增：头像上传物理路径配置
file:
  //自行填写路径
  upload-path: 
